### ISSUE TITLE
does it supports webpack hmr?

### ISSUE THREAD

**Issue by veeramarni** [jomaxx/redux-injectable-reducer#1]
I have been looking something like this for this long. But does this support hot reloading during the development?

**Comment by jomaxx** [comment]
It does not. I'm not sure hmr could be added to something like this. What kind of support are you looking for? Hot reloading of reducers is very tricky and would require replaying of all actions to get a deterministic state. `store.inject` also doesn't support changing a reducer and will throw an error if that is attempted.
